Application.ensure_all_started(:mimic)

Mimic.copy(BB)
Mimic.copy(BB.Actuator)
Mimic.copy(BB.Safety)
Mimic.copy(BB.Robot)
Mimic.copy(BB.Robot.Joint)
Mimic.copy(BB.Robot.Runtime)
Mimic.copy(BB.PubSub)
Mimic.copy(BB.Parameter)
Mimic.copy(BB.Dsl.Info)
Mimic.copy(BB.TUI.Rpc)
Mimic.copy(BB.TUI.App)

ExUnit.start()
